name: deploy angular

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: school-design
    steps:
      - name: pull git repo
        uses: actions/checkout@v2
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 4e981306-f223-41a4-9c19-d3c4b6131a50
          heroku_app_name: school-design-angular
          heroku_email: ravinshnu@dbcyelagiri.edu.in